import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import { ArticleJsonLd, FAQJsonLd } from '../../components/JsonLd'
import ArticleShell from '../../components/ArticleShell'
import { CtaPanel, FaqSection, FeatureBlock } from '../_components/post'

export const metadata: Metadata = {
  title: "I Audited My Own AI Agency's Website. It Was Invisible to Google.",
  description:
    'We ran a full SEO audit on our own AI agency website and discovered it was completely invisible to Google. Here is what went wrong with client-side rendering in Next.js, and exactly how we fixed it.',
  keywords:
    'website SEO audit, Next.js SEO mistakes, why isn\'t my website on Google, client-side rendering SEO, use client SEO, Next.js server components, website invisible to Google, SEO fix',
  openGraph: {
    title: "I Audited My Own AI Agency's Website. It Was Invisible to Google.",
    description:
      'Our entire homepage was client-rendered. Google saw nothing. Here is the full audit and fix.',
    url: 'https://nyclaw.io/blog/i-audited-my-own-website',
    type: 'article',
    siteName: 'NYClaw.io',
  },
  twitter: {
    card: 'summary_large_image',
    title: "I Audited My Own AI Agency's Website. It Was Invisible to Google.",
    description:
      'Our entire homepage was client-rendered. Google saw nothing. Here is the full audit and fix.',
  },
  alternates: {
    canonical: 'https://nyclaw.io/blog/i-audited-my-own-website',
  },
}

const faqItems = [
  {
    question: 'Why isn\'t my website showing up on Google?',
    answer:
      'The most common reasons are: your site is client-side rendered (Google sees an empty page), you have no sitemap.xml telling Google what pages exist, your robots.txt is blocking crawlers, or you have no meta tags or structured data helping Google understand your content. A technical SEO audit can identify exactly which issues apply to your site.',
  },
  {
    question: 'What is client-side rendering and why is it bad for SEO?',
    answer:
      'Client-side rendering (CSR) means your website content is generated by JavaScript in the browser after the page loads. Search engines like Google primarily read the initial HTML your server sends. If that HTML is mostly empty — just a shell with script tags — Google sees a blank page. Server-side rendering (SSR) sends fully formed HTML so search engines can read every word immediately.',
  },
  {
    question: 'How do I check if my website is invisible to search engines?',
    answer:
      'Right-click anywhere on your homepage and select "View Page Source." If you see your actual text content (headlines, paragraphs, service descriptions), your site is server-rendered and visible. If you see mostly empty HTML with a bunch of JavaScript file references and a single div like <div id="__next"></div>, your content is client-rendered and likely invisible to search engines.',
  },
  {
    question: 'What is structured data and why does it matter?',
    answer:
      'Structured data (JSON-LD) is machine-readable code you add to your pages that tells search engines exactly what your content is — a business, an article, a FAQ, a product. It helps Google display rich results (star ratings, FAQ dropdowns, business info panels) and helps AI search tools like ChatGPT and Perplexity cite your content accurately.',
  },
  {
    question: 'How long does it take to fix SEO problems?',
    answer:
      'The technical fixes themselves can often be implemented in a few days to a week. However, seeing results in Google takes longer — typically 2 to 8 weeks for Google to re-crawl and re-index your site, and 2 to 6 months to see meaningful ranking improvements. The sooner you fix the issues, the sooner the clock starts.',
  },
]

export default function BlogPost() {
  return (
    <>
      <ArticleJsonLd
        title="I Audited My Own AI Agency's Website. It Was Invisible to Google."
        description="We ran a full SEO audit on our own AI agency website and discovered it was completely invisible to Google. Here is what went wrong and how we fixed it."
        url="https://nyclaw.io/blog/i-audited-my-own-website"
        datePublished="2026-04-07"
      />
      <FAQJsonLd items={faqItems} />

      <ArticleShell
        backHref="/blog"
        backLabel="Blog"
        tags={['SEO Audit']}
        meta="April 7, 2026 · 12 min read"
        title="I Audited My Own AI Agency's Website. It Was Invisible to Google."
        deck="I built an AI agency website. It looked amazing. Google couldn't see a single word on it."
        related={[
          { href: '/knowledge', title: 'Knowledge Base' },
          { href: '/services/ai-automation', title: 'AI Automation Services' },
        ]}
      >
        <h2>What Happened</h2>
        <p>
          We launched <Link href="/">nyclaw.io</Link> with everything you would want from an AI
          agency site. Beautiful design. Clear messaging. Transparent pricing. An explanation of our{' '}
          <Link href="/services/ai-consulting">OODA Loop consulting framework</Link>. A contact
          form. Service pages for <Link href="/services/ai-automation">AI automation</Link> and
          AI-powered marketing.
        </p>
        <p>
          We built it on Next.js — one of the most popular modern web frameworks. We used Tailwind
          CSS for styling. We deployed it on Vercel. Everything loaded fast, looked clean, and
          worked perfectly on mobile.
        </p>
        <p>
          There was just one problem: traffic was zero. Not low. <strong>Zero.</strong>
        </p>
        <p>
          Weeks went by. No organic search impressions. No clicks. Nothing in Google Search Console.
          We were getting more traffic from telling people the URL in conversation than from the
          entire internet.
        </p>
        <p>
          So we did what any self-respecting AI agency should do: we audited ourselves. What we
          found was embarrassing, educational, and — if you have a website built on a modern
          JavaScript framework — probably happening to you too.
        </p>

        <h2>The Audit: 8 Things We Got Wrong</h2>
        <p>
          We went through our site with fresh eyes and a technical checklist. Here is every issue we
          found, in order of severity.
        </p>

        <FeatureBlock title="1. The homepage was entirely client-rendered">
          This was the big one. Our homepage component had <code>&apos;use client&apos;</code> at the
          top of the file. In Next.js App Router, that single directive tells the framework:
          &quot;Do not render this on the server. Ship it as JavaScript and let the browser handle
          it.&quot;
        </FeatureBlock>
        <p>
          What that means for SEO: when Google&apos;s crawler requests our homepage, it receives an
          HTML file that looks roughly like this:
        </p>
        <pre>{`<html>
  <body>
    <div id="__next"></div>
    <script src="/_next/static/chunks/main.js"></script>
  </body>
</html>`}</pre>
        <p>
          That is it. No headline. No service descriptions. No pricing. No contact info. Just an
          empty container and a JavaScript file that the browser is supposed to execute to fill in
          the content. Google&apos;s crawler <em>can</em> execute JavaScript, but it is slower, less
          reliable, and deprioritized. For a new site with no domain authority, it meant we were
          effectively invisible.
        </p>

        <FeatureBlock title="2. No sitemap.xml">
          A sitemap tells search engines what pages exist on your site and how often they change. We
          did not have one. Google was left to discover our pages by following links — but since the
          homepage was invisible, there were no links to follow. It was a dead end right at the
          front door.
        </FeatureBlock>

        <FeatureBlock title="3. No robots.txt">
          A robots.txt file gives crawlers basic directives: what to crawl, what to skip, where to
          find the sitemap. We had nothing. No explicit rules, no sitemap reference. It is like
          opening a store with no signage — not even a door number.
        </FeatureBlock>

        <FeatureBlock title="4. No structured data (JSON-LD)">
          Structured data is machine-readable markup that tells Google: &quot;This is a professional
          service business, located here, offering these services, at this price range.&quot;
          Without it, Google had to guess what we were. It guessed nothing, because it could not
          even see the page content.
        </FeatureBlock>

        <FeatureBlock title="5. No Open Graph tags">
          When someone shared our link on LinkedIn, Twitter, or iMessage, they got a broken preview.
          No title, no description, no image. It looked like a spam link. This killed any organic
          sharing potential before it started.
        </FeatureBlock>

        <FeatureBlock title="6. Service pages in the nav did not actually exist">
          Our navigation had links to service-specific pages, but those routes were never created.
          They were anchor links on the homepage pointing to sections that only existed once
          JavaScript rendered them. From a search engine&apos;s perspective, those pages did not
          exist at all. From a user&apos;s perspective, clicking them from Google would lead nowhere
          useful.
        </FeatureBlock>

        <FeatureBlock title="7. Only 7 indexable pages total">
          Our competitors in the AI consulting space had 50 to 200+ indexable pages. We had 7. Fewer
          pages means fewer opportunities to rank for search queries, fewer entry points for
          potential clients, and less overall domain authority. Content is surface area, and we had
          almost none.
        </FeatureBlock>

        <FeatureBlock title="8. No FAQ sections">
          FAQ sections serve double duty. They answer real questions your prospects have, and they
          are eligible for Google&apos;s rich results (the expandable Q&amp;A that appears directly
          in search). They are also prime content for AI search tools like ChatGPT, Perplexity, and
          Google AI Overviews to cite. We had none. Easy wins, left on the table.
        </FeatureBlock>

        <h2>Why This Happens (And Why It Is More Common Than You Think)</h2>
        <p>Here is the core issue, explained simply.</p>
        <p>There are two fundamental ways a website can work:</p>

        <div className="grid gap-6 md:grid-cols-2">
          <div className="panel rounded-xl p-6">
            <h4 className="font-medium text-white">Server-Side Rendering (SSR)</h4>
            <p className="mt-2 text-sm leading-relaxed text-zinc-400">
              The server builds the full HTML page and sends it to the browser (and to Google). The
              content is immediately readable. This is how traditional websites work, and it is what
              search engines expect.
            </p>
          </div>
          <div className="panel rounded-xl p-6">
            <h4 className="font-medium text-white">Client-Side Rendering (CSR)</h4>
            <p className="mt-2 text-sm leading-relaxed text-zinc-400">
              The server sends a mostly empty HTML shell. JavaScript runs in the browser and fills
              in the content after the page loads. The content only exists after JavaScript
              executes.
            </p>
          </div>
        </div>

        <p>
          <strong>The analogy:</strong> Server-side rendering is like a storefront with the products
          displayed in the window. Anyone walking by can see what you sell. Client-side rendering is
          like having the world&apos;s best storefront with the shutters permanently closed. The
          products are in there — but only if you walk inside, flip the lights on, and wait for the
          display to assemble itself.
        </p>
        <p>Google is the person walking by. If the shutters are closed, they keep walking.</p>
        <p>
          Here is the frustrating part: Next.js App Router{' '}
          <strong>defaults to Server Components</strong>. Out of the box, it does the right thing.
          But the moment you add <code>&apos;use client&apos;</code> at the top of a file — often
          because you need a single interactive element like a form or a dropdown —{' '}
          <strong>everything in that file becomes client-rendered.</strong> The entire page. All of
          it.
        </p>
        <p>
          This is not a bug. It is how React and Next.js work. But if you do not understand the
          distinction, you can accidentally make your entire site invisible to search engines with
          two words at the top of a file. That is exactly what we did.
        </p>

        <h2>The Fix: What We Changed</h2>
        <p>
          Once we understood the problems, fixing them was straightforward. Here is exactly what we
          did.
        </p>

        <div className="flex flex-col gap-6">
          <div className="panel rounded-xl p-6">
            <h4 className="font-medium text-white">Separated interactive and static content</h4>
            <p className="mt-2 text-[15px] leading-relaxed text-zinc-300">
              Our homepage was 95% static text and 5% interactive elements (a contact form). We
              extracted the form into its own small <code>Client Component</code> and made the main
              page a <code>Server Component</code>. Now 95% of the content ships as ready-to-read
              HTML. The form still works perfectly — it just lives in its own client boundary.
            </p>
          </div>

          <div className="panel rounded-xl p-6">
            <h4 className="font-medium text-white">Added sitemap.ts and robots.ts</h4>
            <p className="mt-2 text-[15px] leading-relaxed text-zinc-300">
              Next.js has built-in API routes for generating sitemaps and robots.txt files. We
              created <code>sitemap.ts</code> and <code>robots.ts</code> in the app directory. Every
              page we want indexed is now listed. Google knows exactly what exists and where to find
              it.
            </p>
          </div>

          <div className="panel rounded-xl p-6">
            <h4 className="font-medium text-white">Added JSON-LD structured data</h4>
            <p className="mt-2 text-[15px] leading-relaxed text-zinc-300">
              We added three schemas: <code>ProfessionalService</code> (who we are and what we do),{' '}
              <code>WebSite</code> (site-level information), and <code>FAQPage</code> (our
              frequently asked questions). Google now understands our business at a machine-readable
              level.
            </p>
          </div>

          <div className="panel rounded-xl p-6">
            <h4 className="font-medium text-white">
              Added Open Graph and Twitter Card meta tags
            </h4>
            <p className="mt-2 text-[15px] leading-relaxed text-zinc-300">
              Every page now has proper OG title, description, and image tags. Links shared on
              social media show rich previews with our branding. This is table stakes for any modern
              website, and we were missing it entirely.
            </p>
          </div>

          <div className="panel rounded-xl p-6">
            <h4 className="font-medium text-white">Built real service pages at real routes</h4>
            <p className="mt-2 text-[15px] leading-relaxed text-zinc-300">
              Instead of anchor links to homepage sections, we created dedicated pages for{' '}
              <Link href="/services/ai-automation">AI Workflow Automation</Link>,{' '}
              <Link href="/services/ai-consulting">AI Strategy &amp; Consulting</Link>, and
              AI-Powered Marketing. Each page has its own metadata, structured data, and content.
              More pages means more surface area for Google to index and rank.
            </p>
          </div>

          <div className="panel rounded-xl p-6">
            <h4 className="font-medium text-white">Added FAQ sections across the site</h4>
            <p className="mt-2 text-[15px] leading-relaxed text-zinc-300">
              Every major page now has a FAQ section with real questions our prospects ask. These
              are marked up with FAQPage schema so they are eligible for Google rich results and AI
              search citations. It is free real estate in the search results.
            </p>
          </div>
        </div>

        <h2>Before &amp; After</h2>
        <p>Here is the difference, side by side.</p>

        <table>
          <thead>
            <tr>
              <th>Metric</th>
              <th>Before</th>
              <th>After</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>What Google sees</td>
              <td>&lt;div id=&quot;__next&quot;&gt;&lt;/div&gt;</td>
              <td>2,000+ words of HTML content</td>
            </tr>
            <tr>
              <td>Structured data schemas</td>
              <td>0</td>
              <td>3 (ProfessionalService, WebSite, FAQPage)</td>
            </tr>
            <tr>
              <td>Sitemap</td>
              <td>None</td>
              <td>10+ pages in sitemap.xml</td>
            </tr>
            <tr>
              <td>Meta tags</td>
              <td>None</td>
              <td>Title, description, OG, Twitter, canonical on every page</td>
            </tr>
            <tr>
              <td>Lighthouse SEO score</td>
              <td>Untested (invisible)</td>
              <td>Targeting 90+</td>
            </tr>
            <tr>
              <td>Social sharing preview</td>
              <td>Broken / blank</td>
              <td>Rich preview with title, description, branding</td>
            </tr>
          </tbody>
        </table>

        <p>
          The site went from a beautiful page that no search engine could read to a fully indexable,
          structured, search-optimized presence — without changing a single word of the visible
          copy. The content was always good. It was just locked behind a JavaScript wall.
        </p>

        <h2>Your Turn: Is YOUR Website Invisible?</h2>
        <p>
          If your website was built on React, Next.js, Vue, Angular, or any modern JavaScript
          framework, there is a real chance you have the same problem. Here is how to check in 60
          seconds.
        </p>

        <div className="panel rounded-xl p-6">
          <h4 className="font-medium text-white">The 60-Second Visibility Test</h4>
          <ol className="mt-4 space-y-3">
            <li>
              <strong>Open your homepage in a browser.</strong>
            </li>
            <li>
              <strong>Right-click anywhere and select &quot;View Page Source.&quot;</strong> (Not
              &quot;Inspect Element&quot; — that shows the JavaScript-rendered version. You want the
              raw HTML the server sends.)
            </li>
            <li>
              <strong>Search for your headline text.</strong> Can you find the actual words that
              appear on your homepage? Your business name? Your service descriptions?
            </li>
            <li>
              <strong>If yes:</strong> Good. Your content is server-rendered and Google can probably
              see it.
            </li>
            <li>
              <strong>If no:</strong> You have the same problem we had. Your site looks great to
              humans but is invisible to search engines.
            </li>
          </ol>
        </div>

        <div className="panel rounded-xl p-6">
          <h4 className="font-medium text-white">While you are at it, check these too:</h4>
          <ul className="mt-4 list-none space-y-3 pl-0">
            <li className="flex items-start gap-3">
              <span className="mt-0.5 font-medium text-cyan-400">-</span>
              <span>
                <strong>Sitemap:</strong> Go to <code>yoursite.com/sitemap.xml</code>. Do you get an
                XML file listing your pages? If you get a 404, you have no sitemap.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="mt-0.5 font-medium text-cyan-400">-</span>
              <span>
                <strong>Robots.txt:</strong> Go to <code>yoursite.com/robots.txt</code>. You should
                see crawl directives and a sitemap reference.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="mt-0.5 font-medium text-cyan-400">-</span>
              <span>
                <strong>Structured data:</strong> Paste your URL into{' '}
                <span className="font-medium text-white">Google&apos;s Rich Results Test</span>.
                Does it find any schemas?
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="mt-0.5 font-medium text-cyan-400">-</span>
              <span>
                <strong>Social preview:</strong> Share your link in a private Slack channel or
                iMessage. Does it show a rich preview with a title and description, or a blank box?
              </span>
            </li>
          </ul>
        </div>

        <p>
          If any of these checks failed, your website is leaking potential traffic every single day.
          The good news: every one of these issues is fixable, usually in less than a week.
        </p>
        <p>
          The bad news: every day you wait is another day your competitors are showing up in search
          results and you are not.
        </p>

        <CtaPanel
          title="Not Sure If Your Site Is Visible?"
          blurb="We will audit your website for free and tell you exactly what Google can and cannot see. No pitch, no commitment. Just the data."
          href="/#contact"
          label="Start a Project"
        />

        <h2>Frequently Asked Questions</h2>
        <FaqSection items={faqItems} />

        {/* Closing CTA — the source had a bare prompt + button, no supporting copy. */}
        <div className="flex flex-col items-center gap-5 border-t border-white/10 pt-10 text-center">
          <p className="text-lg text-zinc-300">Want us to check YOUR site?</p>
          <Link
            href="/#contact"
            className="inline-flex h-11 items-center gap-1 rounded-full bg-white pl-5 pr-3 text-[15px] font-medium text-zinc-950 no-underline transition-opacity hover:opacity-90"
          >
            Start a Project
            <ChevronRight size={17} aria-hidden="true" />
          </Link>
        </div>
      </ArticleShell>
    </>
  )
}
