import type { Metadata } from 'next'
import Link from 'next/link'
import { ArticleJsonLd, FAQJsonLd } from '../../components/JsonLd'

export const metadata: Metadata = {
  title: "I Audited My Own AI Agency's Website. It Was Invisible to Google.",
  description:
    'We ran a full SEO audit on our own AI agency website and discovered it was completely invisible to Google. Here is what went wrong with client-side rendering in Next.js, and exactly how we fixed it.',
  keywords:
    'website SEO audit, Next.js SEO mistakes, why isn\'t my website on Google, client-side rendering SEO, use client SEO, Next.js server components, website invisible to Google, SEO fix',
  openGraph: {
    title: "I Audited My Own AI Agency's Website. It Was Invisible to Google.",
    description:
      'Our entire homepage was client-rendered. Google saw nothing. Here is the full audit and fix.',
    url: 'https://nyclaw.io/blog/i-audited-my-own-website',
    type: 'article',
    siteName: 'NYClaw.io',
  },
  twitter: {
    card: 'summary_large_image',
    title: "I Audited My Own AI Agency's Website. It Was Invisible to Google.",
    description:
      'Our entire homepage was client-rendered. Google saw nothing. Here is the full audit and fix.',
  },
  alternates: {
    canonical: 'https://nyclaw.io/blog/i-audited-my-own-website',
  },
}

const faqItems = [
  {
    question: 'Why isn\'t my website showing up on Google?',
    answer:
      'The most common reasons are: your site is client-side rendered (Google sees an empty page), you have no sitemap.xml telling Google what pages exist, your robots.txt is blocking crawlers, or you have no meta tags or structured data helping Google understand your content. A technical SEO audit can identify exactly which issues apply to your site.',
  },
  {
    question: 'What is client-side rendering and why is it bad for SEO?',
    answer:
      'Client-side rendering (CSR) means your website content is generated by JavaScript in the browser after the page loads. Search engines like Google primarily read the initial HTML your server sends. If that HTML is mostly empty — just a shell with script tags — Google sees a blank page. Server-side rendering (SSR) sends fully formed HTML so search engines can read every word immediately.',
  },
  {
    question: 'How do I check if my website is invisible to search engines?',
    answer:
      'Right-click anywhere on your homepage and select "View Page Source." If you see your actual text content (headlines, paragraphs, service descriptions), your site is server-rendered and visible. If you see mostly empty HTML with a bunch of JavaScript file references and a single div like <div id="__next"></div>, your content is client-rendered and likely invisible to search engines.',
  },
  {
    question: 'What is structured data and why does it matter?',
    answer:
      'Structured data (JSON-LD) is machine-readable code you add to your pages that tells search engines exactly what your content is — a business, an article, a FAQ, a product. It helps Google display rich results (star ratings, FAQ dropdowns, business info panels) and helps AI search tools like ChatGPT and Perplexity cite your content accurately.',
  },
  {
    question: 'How long does it take to fix SEO problems?',
    answer:
      'The technical fixes themselves can often be implemented in a few days to a week. However, seeing results in Google takes longer — typically 2 to 8 weeks for Google to re-crawl and re-index your site, and 2 to 6 months to see meaningful ranking improvements. The sooner you fix the issues, the sooner the clock starts.',
  },
]

export default function BlogPost() {
  return (
    <>
      <ArticleJsonLd
        title="I Audited My Own AI Agency's Website. It Was Invisible to Google."
        description="We ran a full SEO audit on our own AI agency website and discovered it was completely invisible to Google. Here is what went wrong and how we fixed it."
        url="https://nyclaw.io/blog/i-audited-my-own-website"
        datePublished="2026-04-07"
      />
      <FAQJsonLd items={faqItems} />

      <article className="min-h-screen bg-white">
        {/* Hero */}
        <header className="bg-navy text-white py-16 px-6">
          <div className="max-w-3xl mx-auto">
            <div className="flex items-center gap-3 text-sky-blue text-sm font-medium mb-6">
              <Link href="/blog" className="hover:text-white transition-colors">
                Blog
              </Link>
              <span>/</span>
              <span className="text-gray-300">SEO Audit</span>
            </div>
            <h1 className="text-3xl md:text-5xl font-bold leading-tight mb-6">
              I Audited My Own AI Agency&apos;s Website.{' '}
              <span className="text-dark-red">It Was Invisible to Google.</span>
            </h1>
            <p className="text-lg text-gray-300">
              I built an AI agency website. It looked amazing. Google couldn&apos;t see a single word on it.
            </p>
            <div className="mt-6 flex items-center gap-4 text-sm text-gray-400">
              <time dateTime="2026-04-07">April 7, 2026</time>
              <span>|</span>
              <span>12 min read</span>
            </div>
          </div>
        </header>

        {/* Article Body */}
        <div className="py-16 px-6">
          <div className="max-w-3xl mx-auto prose-custom">

            {/* Section 1: What Happened */}
            <section className="mb-14">
              <h2 className="text-2xl md:text-3xl font-bold text-navy mb-6">
                What Happened
              </h2>
              <p className="text-charcoal leading-relaxed mb-4">
                We launched{' '}
                <Link href="/" className="text-sky-blue hover:text-dark-red font-medium transition-colors">
                  nyclaw.io
                </Link>{' '}
                with everything you would want from an AI agency site. Beautiful design. Clear messaging. Transparent pricing. An explanation of our{' '}
                <Link href="/services/ai-consulting" className="text-sky-blue hover:text-dark-red font-medium transition-colors">
                  OODA Loop consulting framework
                </Link>
                . A contact form. Service pages for{' '}
                <Link href="/services/ai-automation" className="text-sky-blue hover:text-dark-red font-medium transition-colors">
                  AI automation
                </Link>
                {' '}and AI-powered marketing.
              </p>
              <p className="text-charcoal leading-relaxed mb-4">
                We built it on Next.js — one of the most popular modern web frameworks. We used Tailwind CSS for styling. We deployed it on Vercel. Everything loaded fast, looked clean, and worked perfectly on mobile.
              </p>
              <p className="text-charcoal leading-relaxed mb-4">
                There was just one problem: traffic was zero. Not low. <strong>Zero.</strong>
              </p>
              <p className="text-charcoal leading-relaxed mb-4">
                Weeks went by. No organic search impressions. No clicks. Nothing in Google Search Console. We were getting more traffic from telling people the URL in conversation than from the entire internet.
              </p>
              <p className="text-charcoal leading-relaxed">
                So we did what any self-respecting AI agency should do: we audited ourselves. What we found was embarrassing, educational, and — if you have a website built on a modern JavaScript framework — probably happening to you too.
              </p>
            </section>

            {/* Section 2: The Audit */}
            <section className="mb-14">
              <h2 className="text-2xl md:text-3xl font-bold text-navy mb-6">
                The Audit: 8 Things We Got Wrong
              </h2>
              <p className="text-charcoal leading-relaxed mb-6">
                We went through our site with fresh eyes and a technical checklist. Here is every issue we found, in order of severity.
              </p>

              {/* Issue 1 */}
              <div className="mb-8 border-l-4 border-dark-red pl-6">
                <h3 className="text-xl font-bold text-navy mb-2">
                  1. The homepage was entirely client-rendered
                </h3>
                <p className="text-charcoal leading-relaxed mb-3">
                  This was the big one. Our homepage component had <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono text-dark-red">&apos;use client&apos;</code> at the top of the file. In Next.js App Router, that single directive tells the framework: &quot;Do not render this on the server. Ship it as JavaScript and let the browser handle it.&quot;
                </p>
                <p className="text-charcoal leading-relaxed mb-3">
                  What that means for SEO: when Google&apos;s crawler requests our homepage, it receives an HTML file that looks roughly like this:
                </p>
                <div className="bg-gray-900 text-gray-200 p-4 rounded-lg font-mono text-sm mb-3 overflow-x-auto">
                  <pre>{`<html>
  <body>
    <div id="__next"></div>
    <script src="/_next/static/chunks/main.js"></script>
  </body>
</html>`}</pre>
                </div>
                <p className="text-charcoal leading-relaxed">
                  That is it. No headline. No service descriptions. No pricing. No contact info. Just an empty container and a JavaScript file that the browser is supposed to execute to fill in the content. Google&apos;s crawler <em>can</em> execute JavaScript, but it is slower, less reliable, and deprioritized. For a new site with no domain authority, it meant we were effectively invisible.
                </p>
              </div>

              {/* Issue 2 */}
              <div className="mb-8 border-l-4 border-dark-red pl-6">
                <h3 className="text-xl font-bold text-navy mb-2">
                  2. No sitemap.xml
                </h3>
                <p className="text-charcoal leading-relaxed">
                  A sitemap tells search engines what pages exist on your site and how often they change. We did not have one. Google was left to discover our pages by following links — but since the homepage was invisible, there were no links to follow. It was a dead end right at the front door.
                </p>
              </div>

              {/* Issue 3 */}
              <div className="mb-8 border-l-4 border-dark-red pl-6">
                <h3 className="text-xl font-bold text-navy mb-2">
                  3. No robots.txt
                </h3>
                <p className="text-charcoal leading-relaxed">
                  A robots.txt file gives crawlers basic directives: what to crawl, what to skip, where to find the sitemap. We had nothing. No explicit rules, no sitemap reference. It is like opening a store with no signage — not even a door number.
                </p>
              </div>

              {/* Issue 4 */}
              <div className="mb-8 border-l-4 border-dark-red pl-6">
                <h3 className="text-xl font-bold text-navy mb-2">
                  4. No structured data (JSON-LD)
                </h3>
                <p className="text-charcoal leading-relaxed">
                  Structured data is machine-readable markup that tells Google: &quot;This is a professional service business, located here, offering these services, at this price range.&quot; Without it, Google had to guess what we were. It guessed nothing, because it could not even see the page content.
                </p>
              </div>

              {/* Issue 5 */}
              <div className="mb-8 border-l-4 border-dark-red pl-6">
                <h3 className="text-xl font-bold text-navy mb-2">
                  5. No Open Graph tags
                </h3>
                <p className="text-charcoal leading-relaxed">
                  When someone shared our link on LinkedIn, Twitter, or iMessage, they got a broken preview. No title, no description, no image. It looked like a spam link. This killed any organic sharing potential before it started.
                </p>
              </div>

              {/* Issue 6 */}
              <div className="mb-8 border-l-4 border-dark-red pl-6">
                <h3 className="text-xl font-bold text-navy mb-2">
                  6. Service pages in the nav did not actually exist
                </h3>
                <p className="text-charcoal leading-relaxed">
                  Our navigation had links to service-specific pages, but those routes were never created. They were anchor links on the homepage pointing to sections that only existed once JavaScript rendered them. From a search engine&apos;s perspective, those pages did not exist at all. From a user&apos;s perspective, clicking them from Google would lead nowhere useful.
                </p>
              </div>

              {/* Issue 7 */}
              <div className="mb-8 border-l-4 border-dark-red pl-6">
                <h3 className="text-xl font-bold text-navy mb-2">
                  7. Only 7 indexable pages total
                </h3>
                <p className="text-charcoal leading-relaxed">
                  Our competitors in the AI consulting space had 50 to 200+ indexable pages. We had 7. Fewer pages means fewer opportunities to rank for search queries, fewer entry points for potential clients, and less overall domain authority. Content is surface area, and we had almost none.
                </p>
              </div>

              {/* Issue 8 */}
              <div className="mb-8 border-l-4 border-dark-red pl-6">
                <h3 className="text-xl font-bold text-navy mb-2">
                  8. No FAQ sections
                </h3>
                <p className="text-charcoal leading-relaxed">
                  FAQ sections serve double duty. They answer real questions your prospects have, and they are eligible for Google&apos;s rich results (the expandable Q&A that appears directly in search). They are also prime content for AI search tools like ChatGPT, Perplexity, and Google AI Overviews to cite. We had none. Easy wins, left on the table.
                </p>
              </div>
            </section>

            {/* Section 3: Why This Happens */}
            <section className="mb-14">
              <h2 className="text-2xl md:text-3xl font-bold text-navy mb-6">
                Why This Happens (And Why It Is More Common Than You Think)
              </h2>
              <p className="text-charcoal leading-relaxed mb-4">
                Here is the core issue, explained simply.
              </p>
              <p className="text-charcoal leading-relaxed mb-4">
                There are two fundamental ways a website can work:
              </p>
              <div className="grid md:grid-cols-2 gap-6 mb-6">
                <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                  <h4 className="font-bold text-navy mb-2">Server-Side Rendering (SSR)</h4>
                  <p className="text-charcoal text-sm leading-relaxed">
                    The server builds the full HTML page and sends it to the browser (and to Google). The content is immediately readable. This is how traditional websites work, and it is what search engines expect.
                  </p>
                </div>
                <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                  <h4 className="font-bold text-navy mb-2">Client-Side Rendering (CSR)</h4>
                  <p className="text-charcoal text-sm leading-relaxed">
                    The server sends a mostly empty HTML shell. JavaScript runs in the browser and fills in the content after the page loads. The content only exists after JavaScript executes.
                  </p>
                </div>
              </div>
              <p className="text-charcoal leading-relaxed mb-4">
                <strong>The analogy:</strong> Server-side rendering is like a storefront with the products displayed in the window. Anyone walking by can see what you sell. Client-side rendering is like having the world&apos;s best storefront with the shutters permanently closed. The products are in there — but only if you walk inside, flip the lights on, and wait for the display to assemble itself.
              </p>
              <p className="text-charcoal leading-relaxed mb-4">
                Google is the person walking by. If the shutters are closed, they keep walking.
              </p>
              <p className="text-charcoal leading-relaxed mb-4">
                Here is the frustrating part: Next.js App Router <strong>defaults to Server Components</strong>. Out of the box, it does the right thing. But the moment you add <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono text-dark-red">&apos;use client&apos;</code> at the top of a file — often because you need a single interactive element like a form or a dropdown — <strong>everything in that file becomes client-rendered.</strong> The entire page. All of it.
              </p>
              <p className="text-charcoal leading-relaxed">
                This is not a bug. It is how React and Next.js work. But if you do not understand the distinction, you can accidentally make your entire site invisible to search engines with two words at the top of a file. That is exactly what we did.
              </p>
            </section>

            {/* Section 4: The Fix */}
            <section className="mb-14">
              <h2 className="text-2xl md:text-3xl font-bold text-navy mb-6">
                The Fix: What We Changed
              </h2>
              <p className="text-charcoal leading-relaxed mb-6">
                Once we understood the problems, fixing them was straightforward. Here is exactly what we did.
              </p>

              <div className="space-y-6">
                <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                  <h4 className="font-bold text-navy mb-2">Separated interactive and static content</h4>
                  <p className="text-charcoal leading-relaxed">
                    Our homepage was 95% static text and 5% interactive elements (a contact form). We extracted the form into its own small <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono">Client Component</code> and made the main page a <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono">Server Component</code>. Now 95% of the content ships as ready-to-read HTML. The form still works perfectly — it just lives in its own client boundary.
                  </p>
                </div>

                <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                  <h4 className="font-bold text-navy mb-2">Added sitemap.ts and robots.ts</h4>
                  <p className="text-charcoal leading-relaxed">
                    Next.js has built-in API routes for generating sitemaps and robots.txt files. We created <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono">sitemap.ts</code> and <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono">robots.ts</code> in the app directory. Every page we want indexed is now listed. Google knows exactly what exists and where to find it.
                  </p>
                </div>

                <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                  <h4 className="font-bold text-navy mb-2">Added JSON-LD structured data</h4>
                  <p className="text-charcoal leading-relaxed">
                    We added three schemas: <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono">ProfessionalService</code> (who we are and what we do), <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono">WebSite</code> (site-level information), and <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono">FAQPage</code> (our frequently asked questions). Google now understands our business at a machine-readable level.
                  </p>
                </div>

                <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                  <h4 className="font-bold text-navy mb-2">Added Open Graph and Twitter Card meta tags</h4>
                  <p className="text-charcoal leading-relaxed">
                    Every page now has proper OG title, description, and image tags. Links shared on social media show rich previews with our branding. This is table stakes for any modern website, and we were missing it entirely.
                  </p>
                </div>

                <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                  <h4 className="font-bold text-navy mb-2">Built real service pages at real routes</h4>
                  <p className="text-charcoal leading-relaxed">
                    Instead of anchor links to homepage sections, we created dedicated pages for{' '}
                    <Link href="/services/ai-automation" className="text-sky-blue hover:text-dark-red font-medium transition-colors">
                      AI Workflow Automation
                    </Link>
                    ,{' '}
                    <Link href="/services/ai-consulting" className="text-sky-blue hover:text-dark-red font-medium transition-colors">
                      AI Strategy & Consulting
                    </Link>
                    , and AI-Powered Marketing. Each page has its own metadata, structured data, and content. More pages means more surface area for Google to index and rank.
                  </p>
                </div>

                <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                  <h4 className="font-bold text-navy mb-2">Added FAQ sections across the site</h4>
                  <p className="text-charcoal leading-relaxed">
                    Every major page now has a FAQ section with real questions our prospects ask. These are marked up with FAQPage schema so they are eligible for Google rich results and AI search citations. It is free real estate in the search results.
                  </p>
                </div>
              </div>
            </section>

            {/* Section 5: Before & After */}
            <section className="mb-14">
              <h2 className="text-2xl md:text-3xl font-bold text-navy mb-6">
                Before & After
              </h2>
              <p className="text-charcoal leading-relaxed mb-6">
                Here is the difference, side by side.
              </p>

              <div className="overflow-x-auto">
                <table className="w-full border-collapse border border-gray-200 text-sm">
                  <thead>
                    <tr className="bg-navy text-white">
                      <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Metric</th>
                      <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Before</th>
                      <th className="border border-gray-300 px-4 py-3 text-left font-semibold">After</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="bg-white">
                      <td className="border border-gray-200 px-4 py-3 font-medium text-navy">What Google sees</td>
                      <td className="border border-gray-200 px-4 py-3 text-dark-red">&lt;div id=&quot;__next&quot;&gt;&lt;/div&gt;</td>
                      <td className="border border-gray-200 px-4 py-3 text-green-700">2,000+ words of HTML content</td>
                    </tr>
                    <tr className="bg-gray-50">
                      <td className="border border-gray-200 px-4 py-3 font-medium text-navy">Structured data schemas</td>
                      <td className="border border-gray-200 px-4 py-3 text-dark-red">0</td>
                      <td className="border border-gray-200 px-4 py-3 text-green-700">3 (ProfessionalService, WebSite, FAQPage)</td>
                    </tr>
                    <tr className="bg-white">
                      <td className="border border-gray-200 px-4 py-3 font-medium text-navy">Sitemap</td>
                      <td className="border border-gray-200 px-4 py-3 text-dark-red">None</td>
                      <td className="border border-gray-200 px-4 py-3 text-green-700">10+ pages in sitemap.xml</td>
                    </tr>
                    <tr className="bg-gray-50">
                      <td className="border border-gray-200 px-4 py-3 font-medium text-navy">Meta tags</td>
                      <td className="border border-gray-200 px-4 py-3 text-dark-red">None</td>
                      <td className="border border-gray-200 px-4 py-3 text-green-700">Title, description, OG, Twitter, canonical on every page</td>
                    </tr>
                    <tr className="bg-white">
                      <td className="border border-gray-200 px-4 py-3 font-medium text-navy">Lighthouse SEO score</td>
                      <td className="border border-gray-200 px-4 py-3 text-dark-red">Untested (invisible)</td>
                      <td className="border border-gray-200 px-4 py-3 text-green-700">Targeting 90+</td>
                    </tr>
                    <tr className="bg-gray-50">
                      <td className="border border-gray-200 px-4 py-3 font-medium text-navy">Social sharing preview</td>
                      <td className="border border-gray-200 px-4 py-3 text-dark-red">Broken / blank</td>
                      <td className="border border-gray-200 px-4 py-3 text-green-700">Rich preview with title, description, branding</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <p className="text-charcoal leading-relaxed mt-6">
                The site went from a beautiful page that no search engine could read to a fully indexable, structured, search-optimized presence — without changing a single word of the visible copy. The content was always good. It was just locked behind a JavaScript wall.
              </p>
            </section>

            {/* Section 6: Your Turn */}
            <section className="mb-14">
              <h2 className="text-2xl md:text-3xl font-bold text-navy mb-6">
                Your Turn: Is YOUR Website Invisible?
              </h2>
              <p className="text-charcoal leading-relaxed mb-4">
                If your website was built on React, Next.js, Vue, Angular, or any modern JavaScript framework, there is a real chance you have the same problem. Here is how to check in 60 seconds.
              </p>

              <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 mb-6">
                <h4 className="font-bold text-navy mb-4">The 60-Second Visibility Test</h4>
                <ol className="list-decimal list-inside space-y-3 text-charcoal leading-relaxed">
                  <li>
                    <strong>Open your homepage in a browser.</strong>
                  </li>
                  <li>
                    <strong>Right-click anywhere and select &quot;View Page Source.&quot;</strong> (Not &quot;Inspect Element&quot; — that shows the JavaScript-rendered version. You want the raw HTML the server sends.)
                  </li>
                  <li>
                    <strong>Search for your headline text.</strong> Can you find the actual words that appear on your homepage? Your business name? Your service descriptions?
                  </li>
                  <li>
                    <strong>If yes:</strong> Good. Your content is server-rendered and Google can probably see it.
                  </li>
                  <li>
                    <strong>If no:</strong> You have the same problem we had. Your site looks great to humans but is invisible to search engines.
                  </li>
                </ol>
              </div>

              <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 mb-6">
                <h4 className="font-bold text-navy mb-4">While you are at it, check these too:</h4>
                <ul className="space-y-3 text-charcoal leading-relaxed">
                  <li className="flex items-start gap-3">
                    <span className="text-sky-blue font-bold mt-0.5">-</span>
                    <span>
                      <strong>Sitemap:</strong> Go to <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono">yoursite.com/sitemap.xml</code>. Do you get an XML file listing your pages? If you get a 404, you have no sitemap.
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-sky-blue font-bold mt-0.5">-</span>
                    <span>
                      <strong>Robots.txt:</strong> Go to <code className="bg-gray-100 px-2 py-0.5 rounded text-sm font-mono">yoursite.com/robots.txt</code>. You should see crawl directives and a sitemap reference.
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-sky-blue font-bold mt-0.5">-</span>
                    <span>
                      <strong>Structured data:</strong> Paste your URL into{' '}
                      <span className="font-medium">Google&apos;s Rich Results Test</span>. Does it find any schemas?
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-sky-blue font-bold mt-0.5">-</span>
                    <span>
                      <strong>Social preview:</strong> Share your link in a private Slack channel or iMessage. Does it show a rich preview with a title and description, or a blank box?
                    </span>
                  </li>
                </ul>
              </div>

              <p className="text-charcoal leading-relaxed mb-4">
                If any of these checks failed, your website is leaking potential traffic every single day. The good news: every one of these issues is fixable, usually in less than a week.
              </p>
              <p className="text-charcoal leading-relaxed">
                The bad news: every day you wait is another day your competitors are showing up in search results and you are not.
              </p>
            </section>

            {/* CTA */}
            <section className="mb-14 bg-navy text-white rounded-xl p-8 md:p-10 text-center">
              <h2 className="text-2xl md:text-3xl font-bold mb-4">
                Not Sure If Your Site Is Visible?
              </h2>
              <p className="text-gray-300 text-lg mb-6 max-w-xl mx-auto">
                We will audit your website for free and tell you exactly what Google can and cannot see. No pitch, no commitment. Just the data.
              </p>
              <Link
                href="/#contact"
                className="btn-red inline-block text-lg px-8 py-3"
              >
                Get a Free AI Audit →
              </Link>
            </section>

            {/* FAQ Section */}
            <section className="mb-14">
              <h2 className="text-2xl md:text-3xl font-bold text-navy mb-8">
                Frequently Asked Questions
              </h2>
              <div className="space-y-6">
                {faqItems.map((item, i) => (
                  <div key={i} className="border border-gray-200 rounded-lg p-6">
                    <h3 className="text-lg font-bold text-navy mb-3">{item.question}</h3>
                    <p className="text-charcoal leading-relaxed">{item.answer}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* Bottom CTA */}
            <section className="text-center py-8 border-t border-gray-200">
              <p className="text-charcoal text-lg mb-4">
                Want us to check YOUR site?
              </p>
              <Link
                href="/#contact"
                className="btn-red inline-block text-lg px-8 py-3"
              >
                Get a Free AI Audit →
              </Link>
              <div className="mt-8 flex justify-center gap-6 text-sm">
                <Link
                  href="/knowledge"
                  className="text-sky-blue hover:text-dark-red font-medium transition-colors"
                >
                  Knowledge Base →
                </Link>
                <Link
                  href="/services/ai-automation"
                  className="text-sky-blue hover:text-dark-red font-medium transition-colors"
                >
                  AI Automation Services →
                </Link>
                <Link
                  href="/blog"
                  className="text-sky-blue hover:text-dark-red font-medium transition-colors"
                >
                  ← Back to Blog
                </Link>
              </div>
            </section>

          </div>
        </div>
      </article>
    </>
  )
}
